# Cosmos Discord Faucet configuration

verbose        = "yes"

[cosmos]
prefix         = "mun"
denomination   = "utmun"

[testnets]
    [testnets.theta]
    node_url = "https://node1.mun.money"
    chain_id = "testmun"
    faucet_address = "mun1mcfq8zy7szal5ymjxxgatz32yvep0edflrzxfl"
    block_explorer_tx = "https://blockexplorer.mun.money/transactions"
    daily_cap = "400000000"
    amount_to_send = "10000000"
    tx_fees = "500"

    [testnets.devnet]
    node_url = "https://node1.mun.money"
    chain_id = "testmun"
    faucet_address = "mun1mcfq8zy7szal5ymjxxgatz32yvep0edflrzxfl"
    block_explorer_tx = "https://blockexplorer.mun.money/transactions"
    daily_cap = "400000000"
    amount_to_send = "10000000"
    tx_fees = "500"
[discord]
bot_token = "MTAzOTAwODI4Mzc2NTI0MzkzNA.GzwB9d.JRLqbkA3YEHR0awWSbeFq6BuUtcD_HuGis_62c"
# comma separated list of channels
channels_to_listen = "general"
# how often user can request tokens from faucet (seconds)
# 10800 = 3  hours
# 86400 = 24 hours
request_timeout    = "1080"